yannis_tether_model_node: # $USER + tether_model_node, @todo: change
  ros__parameters:
    tether_model:
      gravity_const: 9.81
      tether_init_length: 10.0
      tether_diameter: 0.01
      tether_density: 970.0 #source: Sofia
    disturb_mode: "TET_GRAV_FIL_ANG" # possibilities: STRONG_SIDE, CIRCULAR, TET_GRAV_FIL_ANG

yannis_tether_control_node: # $USER + tether_control_node, @todo: change
  ros__parameters:
    uav_type: "MC" # possibilities: MC, VTOL, VTOL-TAILSITTER
    tethered: true
    control_mode: "ATTITUDE"
    hoverThrust: 0.75 # empirically determined, thrust to hover in sim
    attThrustKp: 0.5 # empirically determined, Kp for attitude control
    attThrustKd: 0.05 # empirically determined, Kd for attitude control
    gravComp: 9.81 # z acceleration to compensate for hover