yannis_tether_control_node: # $USER + tether_control_node, @todo: change
  ros__parameters:
    gravComp: 9.81 # z acceleration to compensate for hover
    tethered: true
    uav_type: "MC" # possibilities: MC, VTOL, VTOL-TAILSITTER
    control:
      control_mode: "ATTITUDE"
      hoverThrust: 0.5 # empirically determined, thrust to hover in sim
      attThrustKp: 0.5 # empirically determined, Kp for attitude control
      attThrustKd: 0.05 # empirically determined, Kd for attitude control
    model:
      disturb_mode: "TET_GRAV_FIL_ANG" # possibilities: STRONG_SIDE, CIRCULAR, TET_GRAV_FIL_ANG
      tether_init_length: 10.0
      tether_diameter: 0.01
      tether_density: 970.0 #source: Sofia
    
